export { default as createProduct } from './createProduct'
export { default as getAllProducts } from './getAllProducts'
export { default as getProductById } from './getProductById'
export { default as updateProductById } from './updateProductById'
export { default as deleteProductById } from './deleteProductById'
